version: '3.1'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    networks:
      - wpsite
    secrets:
      - db_root_password
      - db_user
      - db_password

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      PMA_ABSOLUTE_URI: ${SCHEMA:?Schema must be set}://${HOST_URL:?Host URL must be set}/phpma/
    networks:
      - wpsite
      - proxysite
    secrets:
      - db_root_password

  # Wordpress
  wordpress:
    depends_on:
      - db
    build: wordpress
    image: devgulp_wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER_FILE: /run/secrets/db_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_URL: ${HOST_URL:?Host URL must be set}:8000
      WORDPRESS_SCHEMA: ${SCHEMA:?Schema must be set}
      WORDPRESS_TITLE: DevGulp
      WORDPRESS_TAGLINE: A platform built for developers, by developers.
      WORDPRESS_ADMIN_USER_FILE: /run/secrets/wp_admin_user
      WORDPRESS_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WORDPRESS_ADMIN_EMAIL: fake@example.com
      JWT_AUTHENTICATION_SECRET_KEY_FILE: /run/secrets/jwt_auth_key
    networks:
      - wpsite
      - proxysite
    secrets:
      - db_user
      - db_password
      - wp_admin_user
      - wp_admin_password
      - jwt_auth_key

  # Frontend Express/Next
  frontend:
    build:
      context: frontend
      args:
        API_URL: ${SCHEMA:?Schema must be set}://${HOST_URL:?Host URL must be set}:8000
    image: devgulp_frontend
    restart: unless-stopped
    networks:
      - proxysite

  proxy:
    build:
      context: proxy
    image: devgulp_proxy
    restart: unless-stopped
    environment:
      DEPLOY_ENV: ${DEPLOY_ENV:-dev}
      HOST_URL: ${HOST_URL:?Host URL must be set}
    ports:
      - '80:80'
      - '443:443'
      - '8000:8000'
    networks:
      - proxysite


networks:
  wpsite:
  proxysite:

volumes:
  db_data:

secrets:
  db_root_password:
    external: true
  db_user:
    external: true
  db_password:
    external: true
  wp_admin_user:
    external: true
  wp_admin_password:
    external: true
  jwt_auth_key:
    external: true