version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      PMA_ABSOLUTE_URI: ${SCHEMA}://${HOST_URL}/phpma/
    networks:
      - wpsite
      - proxysite

  # Wordpress
  wordpress:
    depends_on:
      - db
    build: wordpress
    image: devgulp_wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_URL: ${HOST_URL}:8000
      WORDPRESS_TITLE: DevGulp
      WORDPRESS_TAGLINE: A platform built for developers, by developers.
      WORDPRESS_DEFAULT_ROLE: author
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: secretpassword
      WORDPRESS_ADMIN_EMAIL: fake@example.com
      JWT_AUTHENTICATION_SECRET_KEY: secretkey
    networks:
      - wpsite
      - proxysite

  # Frontend Express/Next
  frontend:
    build:
      context: frontend
      args:
        API_URL: ${SCHEMA}://${HOST_URL}:8000
    image: devgulp_frontend
    restart: unless-stopped
    networks:
      - proxysite

  proxy:
    build:
      context: proxy
    image: devgulp_proxy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '8000:8000'
    networks:
      - proxysite


networks:
  wpsite:
  proxysite:
volumes:
  db_data:
