module.exports = {
    CLIENT_CONNECTION: 'CLIENT_CONNECTION',
    CLIENT_DISCONNECTION: 'CLIENT_DISCONNECTION',
    SERVER_CONNECTION: 'SERVER_CONNECTION',
    SERVER_DISCONNECTION: 'SERVER_DISCONNECTION',
    CLIENT_CHAT_MESSAGE: 'CLIENT_CHAT_MESSAGE',
    SERVER_CHAT_MESSAGE: 'SERVER_CHAT_MESSAGE',
};
